ALTER TABLE `DrugSaleItem`
  ADD COLUMN `taxableAmount` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `gstPercentage` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `cGstPercentage` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `sGstPercentage` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `iGstPercentage` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `gstAmount` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `cGstAmount` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `sGstAmount` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `iGstAmount` DOUBLE NOT NULL DEFAULT 0;
