/*
  Warnings:

  - You are about to alter the column `type` on the `patientidentification` table. The data in that column could be lost. The data in that column will be cast from `VarChar(191)` to `Enum(EnumId(6))`.

*/
-- AlterTable
ALTER TABLE `patientidentification` MODIFY `type` ENUM('BIRTH_CERTIFICATE', 'CONSENT_FORM', 'DEATH_CERTIFICATE', 'EMPLOYMENT_CODE_OF_CONDUCT_DOCUMENT', 'EMPLOYMENT_EXPERIENCE_LETTER', 'EMPLOYMENT_LEGAL_DOCUMENT', 'EMPLOYMENT_OFFER_LETTER', 'EMPLOYMENT_OTHER_DOCUMENT', 'EMPLOYMENT_PAY_SLIP_PAY_ADVICE', 'EMPLOYMENT_RECOMMENDATION_LETTER', 'EMPLOYMENT_ROLES_AND_RESPONSIBILITIES', 'EMPLOYMENT_TERMINATION_LETTER', 'EMPLOYMENT_TERMS_AND_CONDITIONS_DOCUMENT', 'IDENTIFICATION_DOCUMENT', 'INSURANCE_DOCUMENT', 'INVOICE_DOCUMENT', 'LAB_REPORT', 'LEGAL_DOCUMENT', 'MEDICAL_CERTIFICATE', 'MEDICO_LEGAL_DOCUMENT', 'OTHER_CERTIFICATE_OR_CORRESPONDENCE', 'OTHER_DOCUMENT', 'PATIENT_TRANSFER_DOCUMENT', 'PAYMENT_RECEIPT', 'PHOTOS', 'PRESCRIPTION', 'PROFILE_PICTURE', 'REPORT', 'TRAVEL_DOCUMENT') NOT NULL;
