-- AlterTable
ALTER TABLE `Module` MODIFY `name` ENUM('USER', 'DASHBOARD', 'COMPANY_DETAILS', 'DOCTOR_MASTER', 'DEPARTMENT_MASTER', 'ROOM_TYPE_MASTER', 'ROOM_MASTER', 'BED_MASTER', 'APPOINTMENT', 'PATIENT_MASTER', 'BILLING_SECTION_MASTER', 'SERVICE_MASTER', 'PATHOLOGY_TEST_MASTER', 'RADIOLOGY_TEMPLATE_MASTER', 'RADIOLOGY_TEST_MASTER', 'IPD_BILL', 'DISCHARGE_PATIENT', 'OPD_BILL', 'CONSULTATION_FILE', 'OPD_QUEUE', 'PATHOLOGY_ORDER', 'RADIOLOGY_ORDER', 'LOCATION_MASTER', 'INVOICE', 'FINANCE_BILLING', 'FINANCE_PAYMENTS', 'PHARMACY_SUPPLIER', 'PHARMACY_DRUG_MASTER', 'PHARMACY_DRUG_CATEGORY_MASTER', 'PHARMACY_PURCHASE_ORDER', 'PHARMACY_GRN', 'PHARMACY_INVENTORY', 'PHARMACY_SALE_BILL', 'INCOME', 'EXPENSE') NOT NULL;

-- CreateTable
CREATE TABLE `CompanyDetails` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL DEFAULT '',
    `address` VARCHAR(191) NOT NULL DEFAULT '',
    `mobile` VARCHAR(191) NOT NULL DEFAULT '',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
