ALTER TABLE `Module` MODIFY `name` ENUM(
  'USER',
  'DASHBOARD',
  'COMPANY_DETAILS',
  'DAY_CARE_IPD',
  'IPD_MLC',
  'DOCTOR_MASTER',
  'DEPARTMENT_MASTER',
  'ROOM_TYPE_MASTER',
  'ROOM_MASTER',
  'BED_MASTER',
  'APPOINTMENT',
  'PATIENT_MASTER',
  'BILLING_SECTION_MASTER',
  'SERVICE_MASTER',
  'PATHOLOGY_TEST_MASTER',
  'RADIOLOGY_TEMPLATE_MASTER',
  'RADIOLOGY_TEST_MASTER',
  'IPD_BILL',
  'DISCHARGE_PATIENT',
  'CANCEL_DISCHARGE_PATIENT',
  'OPD_BILL',
  'CONSULTATION_FILE',
  'OPD_QUEUE',
  'PATHOLOGY_ORDER',
  'RADIOLOGY_ORDER',
  'LOCATION_MASTER',
  'INVOICE',
  'FINANCE_BILLING',
  'FINANCE_PAYMENTS',
  'PHARMACY_SUPPLIER',
  'PHARMACY_DRUG_MASTER',
  'PHARMACY_DRUG_CATEGORY_MASTER',
  'PHARMACY_PURCHASE_ORDER',
  'PHARMACY_GRN',
  'PHARMACY_INVENTORY',
  'PHARMACY_SALE_BILL',
  'INCOME',
  'EXPENSE'
) NOT NULL;

INSERT IGNORE INTO `Module` (`name`, `createdAt`, `updatedAt`)
VALUES ('CANCEL_DISCHARGE_PATIENT', NOW(3), NOW(3));

INSERT IGNORE INTO `Permission` (`moduleId`, `actionId`)
SELECT m.`id`, a.`id`
FROM `Module` m
JOIN `Action` a ON a.`name` = 'UPDATE'
WHERE m.`name` = 'CANCEL_DISCHARGE_PATIENT';
