-- AlterTable
ALTER TABLE `Module` MODIFY `name` ENUM('USER', 'DASHBOARD', 'DOCTOR_MASTER', 'DEPARTMENT_MASTER', 'ROOM_TYPE_MASTER', 'ROOM_MASTER', 'BED_MASTER', 'APPOINTMENT', 'PATIENT_MASTER', 'BILLING_SECTION_MASTER', 'SERVICE_MASTER', 'PATHOLOGY_TEST_MASTER', 'RADIOLOGY_TEST_MASTER', 'IPD_BILL', 'OPD_BILL', 'OPD_QUEUE', 'PATHOLOGY_ORDER', 'RADIOLOGY_ORDER', 'LOCATION_MASTER', 'INVOICE', 'PHARMACY_SUPPLIER', 'PHARMACY_DRUG_MASTER', 'PHARMACY_DRUG_CATEGORY_MASTER', 'PHARMACY_PURCHASE_ORDER', 'PHARMACY_GRN', 'PHARMACY_SALE_BILL', 'INCOME', 'EXPENSE') NOT NULL;

-- CreateTable
CREATE TABLE `Income` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `mode` ENUM('PAYMENT_MODE_DEFAULT', 'CASH', 'CARD_PAYMENT', 'CHEQUE', 'DIGITAL_WALLET', 'INSURANCE', 'INTERNAL_ADJUSTMENTS', 'LOYALTY_CARD', 'NEFT', 'RTGS', 'TDS_AYUSHMAN_BHARAT', 'TDS_CHIRANJIVI_YOJNA', 'TDS_OTHERS', 'TDS', 'OTHER') NOT NULL,
    `amount` DOUBLE NOT NULL,
    `collectedOn` DATETIME(3) NOT NULL,
    `collectedById` INTEGER NOT NULL,
    `category` VARCHAR(191) NOT NULL,
    `description` LONGTEXT NULL,
    `isDeleted` BOOLEAN NOT NULL DEFAULT false,
    `createdBy` INTEGER NULL,
    `updatedBy` INTEGER NULL,
    `deletedBy` INTEGER NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Expense` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `category` VARCHAR(191) NOT NULL,
    `amount` DOUBLE NOT NULL,
    `paymentMode` ENUM('PAYMENT_MODE_DEFAULT', 'CASH', 'CARD_PAYMENT', 'CHEQUE', 'DIGITAL_WALLET', 'INSURANCE', 'INTERNAL_ADJUSTMENTS', 'LOYALTY_CARD', 'NEFT', 'RTGS', 'TDS_AYUSHMAN_BHARAT', 'TDS_CHIRANJIVI_YOJNA', 'TDS_OTHERS', 'TDS', 'OTHER') NOT NULL,
    `dateTime` DATETIME(3) NOT NULL,
    `description` LONGTEXT NULL,
    `isDeleted` BOOLEAN NOT NULL DEFAULT false,
    `createdBy` INTEGER NULL,
    `updatedBy` INTEGER NULL,
    `deletedBy` INTEGER NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Income` ADD CONSTRAINT `Income_collectedById_fkey` FOREIGN KEY (`collectedById`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

INSERT IGNORE INTO `Module` (`name`, `createdAt`, `updatedAt`)
VALUES
  ('INCOME', NOW(), NOW()),
  ('EXPENSE', NOW(), NOW());

INSERT IGNORE INTO `Permission` (`moduleId`, `actionId`)
SELECT m.id, a.id
FROM `Module` m
CROSS JOIN `Action` a
WHERE m.name IN ('INCOME', 'EXPENSE');
