import { ActionType, ModuleType } from "@/generated/prisma/enums";

export const MODULE_ACTION_MATRIX = {
  [ModuleType.USER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.DASHBOARD]: [ActionType.VIEW],
  [ModuleType.COMPANY_DETAILS]: [ActionType.VIEW, ActionType.UPDATE],
  [ModuleType.DOCTOR_MASTER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.DEPARTMENT_MASTER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.ROOM_TYPE_MASTER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.ROOM_MASTER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.BED_MASTER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.APPOINTMENT]: [ActionType.CREATE, ActionType.VIEW],
  [ModuleType.PATIENT_MASTER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
  ],
  [ModuleType.BILLING_SECTION_MASTER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.SERVICE_MASTER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.PATHOLOGY_TEST_MASTER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.RADIOLOGY_TEMPLATE_MASTER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.RADIOLOGY_TEST_MASTER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.IPD_BILL]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.PRINT,
  ],
  [ModuleType.DISCHARGE_PATIENT]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.PRINT,
  ],
  [ModuleType.OPD_BILL]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.PRINT,
  ],
  [ModuleType.CONSULTATION_FILE]: [
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.PRINT,
  ],
  [ModuleType.OPD_QUEUE]: [ActionType.VIEW, ActionType.DELETE],
  [ModuleType.PATHOLOGY_ORDER]: [
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.PRINT,
  ],
  [ModuleType.RADIOLOGY_ORDER]: [
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.PRINT,
  ],
  [ModuleType.LOCATION_MASTER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.INVOICE]: [],
  [ModuleType.FINANCE_BILLING]: [ActionType.VIEW],
  [ModuleType.FINANCE_PAYMENTS]: [ActionType.VIEW],
  [ModuleType.PHARMACY_SUPPLIER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.PHARMACY_DRUG_MASTER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.PHARMACY_DRUG_CATEGORY_MASTER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.PHARMACY_PURCHASE_ORDER]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.PHARMACY_GRN]: [ActionType.CREATE, ActionType.VIEW],
  [ModuleType.PHARMACY_INVENTORY]: [ActionType.VIEW],
  [ModuleType.PHARMACY_SALE_BILL]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
    ActionType.PRINT,
  ],
  [ModuleType.INCOME]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
  [ModuleType.EXPENSE]: [
    ActionType.CREATE,
    ActionType.UPDATE,
    ActionType.VIEW,
    ActionType.DELETE,
  ],
} as unknown as Record<ModuleType, ActionType[]>;
